import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  iphoneProMax: {
    backgroundColor: '#ffffff',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  div: {
    backgroundColor: '#ffffff',
    height: 932,
    overflow: 'hidden',
    position: 'relative',
    width: 430,
  },
  overlap: {
    backgroundColor: '#2e3192',
    borderRadius: 388,
    height: 694,
    left: -186,
    position: 'absolute',
    top: -164,
    width: 776,
  },
  maskGroup: {
    height: 530,
    left: 186,
    position: 'absolute',
    top: 164,
    width: 430,
  },
  textWrapper: {
    color: '#ffffff',
    fontFamily: 'Poppins-Bold, Helvetica',
    fontSize: 30,
    fontWeight: '700',
    left: 227,
    letterSpacing: 0,
    lineHeight: 'normal',
    position: 'absolute',
    top: 528,
    width: 389,
  },
  ecgtvLogoigg: {
    height: 190,
    left: 251,
    objectFit: 'cover',
    position: 'absolute',
    top: 318,
    width: 300,
  },
  fieldOfficersMeter: {
    color: '#2e3192',
    fontFamily: 'Poppins-Medium, Helvetica',
    fontSize: 12,
    fontWeight: '500',
    left: 76,
    letterSpacing: 0,
    lineHeight: 'normal',
    position: 'absolute',
    top: 835,
  },
  overlapGroup: {
    height: 252,
    left: 50,
    position: 'absolute',
    top: 566,
    width: 467,
  },
  overlap2: {
    height: 252,
    left: 23,
    position: 'absolute',
    top: 0,
    width: 444,
  },
  rectangle: {
    height: 252,
    left: 189,
    objectFit: 'cover',
    position: 'absolute',
    top: 0,
    width: 255,
  },
  component: {
    height: 62,
    left: 0,
    position: 'absolute',
    top: 5,
    width: 284,
  },
  overlapGroup2: {
    backgroundColor: '#dedff7',
    border: '1px solid',
    borderColor: '#2e3192',
    borderRadius: 33,
    height: 62,
    left: -23,
    position: 'relative',
    width: 330,
  },
  user: {
    height: 29,
    left: 26,
    position: 'absolute',
    top: 15,
    width: 29,
  },
  textWrapper2: {
    color: '#2e3192',
    fontFamily: 'Poppins-Medium, Helvetica',
    fontSize: 14,
    fontWeight: '500',
    left: 78,
    letterSpacing: 0,
    lineHeight: 'normal',
    position: 'absolute',
    top: 20,
    width: 73,
  },
  overlapWrapper: {
    height: 62,
    left: 0,
    position: 'absolute',
    top: 167,
    width: 284,
  },
  divWrapper: {
    backgroundColor: '#2e3192',
    borderRadius: 33,
    height: 62,
    left: -23,
    position: 'relative',
    width: 330,
  },
  textWrapper3: {
    color: '#ffffff',
    fontFamily: 'Poppins-Bold, Helvetica',
    fontSize: 20,
    fontWeight: '700',
    left: 128,
    letterSpacing: 0,
    lineHeight: 'normal',
    position: 'absolute',
    top: 15,
    width: 74,
  },
  overlapGroupWrapper: {
    height: 62,
    left: 0,
    position: 'absolute',
    top: 87,
    width: 284,
  },
  user2: {
    color: '#2e3192',
    fontFamily: 'Poppins-Medium, Helvetica',
    fontSize: 14,
    fontWeight: '500',
    left: 78,
    letterSpacing: 0,
    lineHeight: 'normal',
    position: 'absolute',
    top: 20,
    width: 69,
  },
  password: {
    height: 25,
    left: 27,
    position: 'absolute',
    top: 15,
    width: 25,
  },
  invisible: {
    height: 30,
    left: 248,
    position: 'absolute',
    top: 21,
    width: 30,
  },
  rectangle2: {
    backgroundColor: '#b8b5b5',
    height: 1,
    left: 157,
    position: 'absolute',
    top: 248,
    width: 150,
  },
  rectangle3: {
    backgroundColor: '#b8b5b5',
    height: 1,
    left: 0,
    position: 'absolute',
    top: 248,
    width: 150,
  },
});

export default styles;
